### ISSUE TITLE
Parsing only last Record

### ISSUE THREAD

**Issue by Rajeshkmsc** [jmandel/ccda-to-json#1]
From the given example.xml file parser is parsing only last record of Vitals/Meditation/Immunization. need help to List all given vitals/Meditation/Immunization.

Thanks
Rajesh.k

**Comment by jmandel** [comment]
Hi @Rajeshkmsc!  Thanks for your report!

I've updated the repo to fix this bug:
https://github.com/jmandel/ccda-to-json/commit/ace6ca6544fb2887f8d77de48eeb3cb656ca108a

Note that I also changed the syntax for obtaining the CCDA Parser: there's now a window variable called window.CCDAParser that you can use directly, rather than `require`-ing it.

Overall I might steer you towards [BlueButton.js](https://github.com/blue-button/bluebutton.js), which has been more actively maintained. The BB.js JSON representation is converging towards what you see in this repo, and it's probably a better bet moving forward.

**Comment by Rajeshkmsc** [comment]
Hi jmandel,

 Lot of Thanks for your updates.  I am using "BluButton" It's working good. Great work. 

Thanks
Rajesh.k
